openapi: 3.0.3
info:
  title: Passengers 
  version: 1.0.0

tags:
  - name: vehicle


paths:
  /passengers:
    post:
      tags:
        - passenger
      summary: Add a new passenger 
      description: Add a new passenger 
      operationId: addPassenger
      requestBody:
        description: Create a new passenger 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Passenger'
          application/xml:
            schema:
              $ref: '#/components/schemas/Passenger'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Passenger'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passenger'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Passenger'
        '400':
          description: Invalid input
        '422':
          description: Validation exception

  
  /passengers/{Id}:
    get:
      tags:
        - passenger
      summary: Find passenger by ID
      description: Returns a single passenger
      operationId: getPassengerById
      parameters:
        - name: Id
          in: path
          description: ID of passenger to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passenger'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Passenger'
        '400':
          description: Invalid ID supplied
        '404':
          description: Passenger not found
    
   
          
          
  /passengers/{Id}/trips:
    
    get:
      tags:
        - trips
      summary: Find trip by ID
      description: Returns a single trip
      operationId: getTripByPassengerId
      parameters:
        - name: Id
          in: path
          description: Get one passenger trips
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passenger'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Passenger'
        '400':
          description: Invalid ID supplied
        '404':
          description: Passenger not found
          
    post:
      tags:
      - trips
      summary: Post trips 
      description: Post trips for an existing passenger
      operationId: postTripByPassengerId
      parameters:
        - name: Id
          in: path
          description: Post one passenger trips
          required: true
          schema:
            type: string
      requestBody:
        description: Post a new Trip/s 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Passenger'
          application/xml:
            schema:
              $ref: '#/components/schemas/Passenger'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Passenger'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passenger'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Passenger'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
    

  
components:
  schemas:
    
    Passenger:
      required:
        - passengerId
      type: object
      properties:
        passengerId:
          type: string
          example: P-456
        licensePlate:
          type: string
          example: Ana Gómez
        email:
          type: string
          example: ana.gomez@example.com
        phone:
          type: string 
          example: +1987654321
        preferredPaymentMethod:
          type: string
          example: cash
        registeredAt:
          type: string
          example: 2024-07-01T10:30:00Z #fecha
        
        
        trip:
            $ref: '#/components/schemas/Trip'
       
      xml:
        name: Trip
        
    Trip:
      required:
        - tripId
        - name
        - contact
      type: object
      properties:
        tripId:
          type: string
          example: T-1003
        vehicleId:
          type: string
          example: V-457
        routeId:
          type: string
          example: 124
        passengerId:
          type: string
          example: P-002
        startTime:
          type: string
          example: 2024-07-04T10:00:00Z
        endTime:
          type: string
          example: 2024-07-04T10:30:00Z
        startStop:
          type: string
          example: Estación Norte
        endStop:
          type: string
          example: Centro Comercial
        fare:
          type: number
          example: 2.20
